pipeline:
  name: "VladCD test "
  identifier: VladCD_test
  projectIdentifier: Lab_Vladimir
  orgIdentifier: training_13thNov
  tags: {}
  stages:
    - stage1:
        name: Vladtest
       // identifier: Vladtest
        description: "This is Vlad"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Vladservice
          environment:
            environmentRef: org.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
